"""The classification decision tree, especially where its gates differ.

`GameManager.GenerateVenueTrack()` uses three *different* conditions:

    milo fallback     <- VenueTrack.IsEmpty          (all five lists)
    fog generation    <- !ChartHasFog()              (stage list only)
    lighting autogen  <- Lighting.Count == 0         (lighting list only)

Treating them as one condition is the single most likely way to misclassify a
song, so each divergence gets its own test.
"""

from dataclasses import dataclass

from tests.venue_fixtures import (
    midi_file, note_off, note_on, text_event, track_chunk, venue_midi,
)
from venue_scan.classify import classify, richness
from venue_scan.discover import SongLoad


@dataclass
class FakeRef:
    """Stands in for a SongRef so tests can supply bytes directly."""

    load_result: SongLoad
    kind: str = "sng"
    path: str = "/fake/song.sng"
    asset_path: str | None = None

    @property
    def song_id(self) -> str:
        return self.path

    def load(self) -> SongLoad:
        return self.load_result


def classify_bytes(chart=None, milo=None, chart_format="mid", metadata=None):
    return classify(FakeRef(SongLoad(chart_format, chart, milo, metadata or {})))


def test_authored_midi_venue_is_reported_as_the_source():
    chart = venue_midi([
        (0, text_event("[lighting (manual_warm)]")),
        (480, text_event("[lighting (stomp)]")),
    ])
    record = classify_bytes(chart)
    assert record.venue_source == "midi"
    assert record.counts["lighting"] == 2
    assert record.autogen_lighting is False
    assert record.autogenerated is False


def test_chart_format_songs_never_carry_venue():
    """YARG's .chart reader has no venue path at all."""
    record = classify_bytes(b"[Song]\n{\n}\n", chart_format="chart")
    assert record.venue_source == "none"
    assert record.autogen_lighting is True
    assert record.autogenerated is True


def test_missing_venue_track_falls_through_to_autogeneration():
    chart = midi_file([track_chunk("PART DRUMS", [])])
    record = classify_bytes(chart)
    assert record.has_venue_track is False
    assert record.venue_source == "none"
    assert record.autogen_lighting is True


def test_camera_cuts_alone_block_the_milo_load_but_not_lighting_autogen():
    """The core divergence: IsEmpty is false, yet Lighting.Count is still 0.

    The song keeps its authored cuts, never reads its Milo, and *still* gets
    synthesized lighting on top.
    """
    chart = venue_midi([
        (0, text_event("[coop_d_near]")),
        (480, text_event("[coop_all_far]")),
        (480, text_event("[coop_g_near]")),
    ])
    milo = _milo_with_lighting()
    record = classify_bytes(chart, milo)

    assert record.venue_source == "midi"       # not "milo" — the Milo was skipped
    assert record.counts["camera_cuts"] > 0
    assert record.counts["lighting"] == 0
    assert record.autogen_lighting is True     # despite an authored venue
    assert record.autogenerated is True


def test_milo_is_loaded_only_when_every_list_is_empty():
    chart = midi_file([track_chunk("PART DRUMS", [])])
    record = classify_bytes(chart, _milo_with_lighting())
    assert record.venue_source == "milo"
    assert record.counts["lighting"] > 0
    assert record.autogen_lighting is False


def test_fog_autogeneration_runs_even_on_a_fully_authored_venue():
    """ChartHasFog is independent of the other two gates."""
    chart = venue_midi([(0, text_event("[lighting (stomp)]"))])
    record = classify_bytes(chart)
    assert record.venue_source == "midi"
    assert record.autogen_lighting is False
    assert record.autogen_fog is True          # no fog authored -> YARG adds it


def test_authored_fog_suppresses_fog_autogeneration():
    chart = venue_midi([
        (0, text_event("[lighting (stomp)]")),
        (480, text_event("[FogOn]")),
    ])
    record = classify_bytes(chart)
    assert record.autogen_fog is False


def test_unknown_text_does_not_make_a_venue_non_empty():
    """YARG drops unmatched text, so it must not suppress the Milo load."""
    chart = venue_midi([(0, text_event("[charter_was_here]"))])
    record = classify_bytes(chart, _milo_with_lighting())
    assert record.unknown_text == ["charter_was_here"]
    assert record.venue_source == "milo"


def test_truncation_is_recorded():
    chart = venue_midi([
        (0, note_on(48)), (480, note_off(48)),
        (10, note_off(72)),
    ])
    record = classify_bytes(chart)
    assert record.venue_truncated is True


def test_errors_are_captured_rather_than_raised():
    record = classify_bytes(b"not a midi file at all")
    assert record.error is not None
    assert record.venue_source == "none"


def test_missing_chart_is_reported():
    record = classify_bytes(None, chart_format=None)
    assert record.error == "no chart member"


def test_metadata_is_carried_onto_the_record():
    chart = venue_midi([])
    record = classify_bytes(chart, metadata={"artist": "A", "name": "B", "charter": "C"})
    assert (record.artist, record.title, record.charter) == ("A", "B", "C")


def test_richness_ranks_authored_lighting_above_camera_only():
    lit = classify_bytes(venue_midi([
        (0, text_event("[lighting (stomp)]")),
        (10, text_event("[lighting (verse)]")),
    ]))
    cuts = classify_bytes(venue_midi([
        (0, text_event("[coop_d_near]")),
        (480, text_event("[coop_all_far]")),
    ]))
    assert richness(lit) > richness(cuts)
    assert richness(classify_bytes(b"x", chart_format="chart")) == 0


def _milo_with_lighting() -> bytes:
    """A minimal uncompressed Milo whose song.anim holds one lighting event."""
    import struct

    body = bytearray(b"song.anim")
    body += b"lightpreset_interp" + bytes(5)
    body += struct.pack(">I", 1)                  # one event
    name = b"loop_warm"
    body += struct.pack(">I", len(name)) + name
    body += struct.pack(">f", 60.0)               # 60 frames -> 2.0s

    header = struct.pack("<IIII", 0xCABEDEAF, 32, 1, len(body))
    header += struct.pack("<I", len(body))
    return header.ljust(32, b"\0") + bytes(body)
