"""Decide what lighting a song actually has.

This mirrors `GameManager.GenerateVenueTrack()` in the YARG Unity repo::

    if (Chart.VenueTrack.IsEmpty)                 // ALL FIVE lists empty
        SongChart.LoadVenueFromMilo(...);

    if (!preset.ChartHasFog(Chart))               // no fog anywhere
        Chart = preset.GenerateFogEvents(Chart);

    if (Chart.VenueTrack.Lighting.Count == 0)     // lighting list ONLY
        Chart = preset.GenerateLightingEvents(Chart);

The three conditions are different, and conflating them is the most common way
to misclassify a song. A chart with authored camera cuts but no lighting cues
never loads its Milo *and* still receives synthesized lighting.
"""

from __future__ import annotations

import hashlib
from dataclasses import asdict, dataclass, field

from . import midi as midi_reader
from .discover import SongRef
from .venue_midi import VENUE_TRACK_NAME, build_venue_track, parse_venue_track
from .venue_milo import ANIMATION_MEMBER, MiloError, decompress, parse_milo_venue
from .venue_track import VenueTrack

#: Chart formats that can carry a VENUE track at all. `.chart` (Clone Hero) and
#: `.txt` (UltraStar) have no venue section in YARG's readers.
MIDI_FORMATS = ("mid", "midi")

#: How many unmatched text events to keep per song.
UNKNOWN_TEXT_SAMPLE = 12


@dataclass
class SongVenueRecord:
    """One line of the venue index."""

    song_id: str
    kind: str
    path: str
    asset_path: str | None = None
    artist: str = ""
    title: str = ""
    charter: str = ""

    chart_format: str | None = None
    chart_sha1: str | None = None
    has_venue_track: bool = False
    has_milo: bool = False
    #: Whether the Milo actually contains a `song.anim` member. Recorded even
    #: when the Milo is never loaded, because "ships a Milo" and "ships venue
    #: data in that Milo" turn out to be very different populations.
    milo_has_anim: bool = False

    #: "midi" | "milo" | "none"
    venue_source: str = "none"
    counts: dict = field(default_factory=dict)
    histograms: dict = field(default_factory=dict)
    unknown_text: list = field(default_factory=list)
    venue_truncated: bool = False

    autogen_lighting: bool = True
    autogen_fog: bool = True
    #: What YARG would set on VenueTrack.AutoGenerated.
    autogenerated: bool = True

    error: str | None = None

    def to_json(self) -> dict:
        return asdict(self)


def classify(ref: SongRef) -> SongVenueRecord:
    """Load one song and classify its venue. Never raises."""
    record = SongVenueRecord(song_id=ref.song_id, kind=ref.kind, path=ref.path,
                             asset_path=ref.asset_path)
    try:
        return _classify(ref, record)
    except Exception as exc:  # noqa: BLE001 - a 35k-song scan must not die here
        record.error = f"{type(exc).__name__}: {exc}"
        return record


def _classify(ref: SongRef, record: SongVenueRecord) -> SongVenueRecord:
    load = ref.load()
    _apply_metadata(record, load.metadata)
    record.chart_format = load.chart_format
    record.has_milo = load.milo_bytes is not None
    if load.milo_bytes is not None:
        record.milo_has_anim = milo_has_animation(load.milo_bytes)

    if load.chart_bytes is None:
        record.error = "no chart member"
        return record
    record.chart_sha1 = hashlib.sha1(load.chart_bytes).hexdigest()

    venue = VenueTrack()

    # Step 1-3: authored MIDI venue.
    if record.chart_format in MIDI_FORMATS:
        track = midi_reader.find_track(load.chart_bytes, VENUE_TRACK_NAME)
        if track is not None:
            record.has_venue_track = True
            parsed = parse_venue_track(track)
            record.venue_truncated = parsed.truncated
            record.unknown_text = _dedupe(parsed.unknown_text)[:UNKNOWN_TEXT_SAMPLE]
            venue = build_venue_track(parsed.events)
            if not venue.is_empty:
                record.venue_source = "midi"

    # Step 4: the Milo fallback needs ALL FIVE lists empty, not just lighting.
    if venue.is_empty and load.milo_bytes is not None:
        try:
            milo_venue = parse_milo_venue(load.milo_bytes)
        except MiloError as exc:
            record.error = f"milo: {exc}"
        else:
            venue.extend(milo_venue)
            if not venue.is_empty:
                record.venue_source = "milo"

    # Step 5: the two auto-generation gates, which differ from each other and
    # from the Milo gate above.
    record.autogen_lighting = len(venue.lighting) == 0
    record.autogen_fog = not venue.has_fog
    record.autogenerated = record.autogen_lighting

    record.counts = venue.counts()
    record.histograms = venue.histograms()
    return record


def milo_has_animation(data: bytes) -> bool:
    """Does this Milo carry a `song.anim` member at all?

    Most shipped Milos are ~2.5 KB stubs with no animation data, so this
    distinguishes "the Milo fallback was blocked" from "there was nothing to
    fall back to".
    """
    try:
        return ANIMATION_MEMBER in decompress(data)
    except Exception:  # noqa: BLE001 - a probe must never fail the scan
        return False


def _apply_metadata(record: SongVenueRecord, metadata: dict) -> None:
    record.artist = metadata.get("artist", "")
    record.title = metadata.get("name", "") or metadata.get("title", "")
    record.charter = metadata.get("charter", "") or metadata.get("frets", "")


def _dedupe(values: list[str]) -> list[str]:
    seen: dict[str, None] = {}
    for value in values:
        seen.setdefault(value, None)
    return list(seen)


def richness(record: SongVenueRecord) -> int:
    """Rank for the fixture shortlist: how much authored venue a song carries."""
    if record.venue_source == "none":
        return 0
    counts = record.counts
    # Lighting is what the bridge renders, so weight it hardest; the other
    # categories still indicate a hand-authored venue worth using as a fixture.
    return (
        counts.get("lighting", 0) * 4
        + counts.get("post_processing", 0) * 2
        + counts.get("stage", 0) * 3
        + counts.get("performer", 0) * 3
        + counts.get("camera_cuts", 0)
    )
